// Generated by gencpp from file weather_station/local_weather.msg
// DO NOT EDIT!


#ifndef WEATHER_STATION_MESSAGE_LOCAL_WEATHER_H
#define WEATHER_STATION_MESSAGE_LOCAL_WEATHER_H

#include <ros/service_traits.h>


#include <weather_station/local_weatherRequest.h>
#include <weather_station/local_weatherResponse.h>


namespace weather_station
{

struct local_weather
{

typedef local_weatherRequest Request;
typedef local_weatherResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct local_weather
} // namespace weather_station


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::weather_station::local_weather > {
  static const char* value()
  {
    return "175f12046f41ab94b7e23ad440a590f4";
  }

  static const char* value(const ::weather_station::local_weather&) { return value(); }
};

template<>
struct DataType< ::weather_station::local_weather > {
  static const char* value()
  {
    return "weather_station/local_weather";
  }

  static const char* value(const ::weather_station::local_weather&) { return value(); }
};


// service_traits::MD5Sum< ::weather_station::local_weatherRequest> should match 
// service_traits::MD5Sum< ::weather_station::local_weather > 
template<>
struct MD5Sum< ::weather_station::local_weatherRequest>
{
  static const char* value()
  {
    return MD5Sum< ::weather_station::local_weather >::value();
  }
  static const char* value(const ::weather_station::local_weatherRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::weather_station::local_weatherRequest> should match 
// service_traits::DataType< ::weather_station::local_weather > 
template<>
struct DataType< ::weather_station::local_weatherRequest>
{
  static const char* value()
  {
    return DataType< ::weather_station::local_weather >::value();
  }
  static const char* value(const ::weather_station::local_weatherRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::weather_station::local_weatherResponse> should match 
// service_traits::MD5Sum< ::weather_station::local_weather > 
template<>
struct MD5Sum< ::weather_station::local_weatherResponse>
{
  static const char* value()
  {
    return MD5Sum< ::weather_station::local_weather >::value();
  }
  static const char* value(const ::weather_station::local_weatherResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::weather_station::local_weatherResponse> should match 
// service_traits::DataType< ::weather_station::local_weather > 
template<>
struct DataType< ::weather_station::local_weatherResponse>
{
  static const char* value()
  {
    return DataType< ::weather_station::local_weather >::value();
  }
  static const char* value(const ::weather_station::local_weatherResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEATHER_STATION_MESSAGE_LOCAL_WEATHER_H
